### ISSUE TITLE
i386 build error with the last ffmpeg version (1.2.1)

### ISSUE THREAD

**Issue by Ronan0912** [lvjian700/ffmpegc#1]
There is a compilation error with the i386 platform and the last version of ffmpeg (1.2.1) ; "cc1: error in backend: Ran out of registers during register allocation!
make: **\* [libavcodec/h264_cabac.o] Error 1"

With the configure option "--disable-asm", it compiles without any problem (http://www.tangentsoftworks.com/blog/2012/11/12/how-to-prepare-your-mac-for-ios-development-with-ffmpeg-libraries/)

Ronan

**Comment by lvjian700** [comment]
@Ronan0912 I can not compile ffmpeg 1.2.1.  
I change the version from 1.0.1 to 1.2.1 and run my compile script. I get this error:
libavcodec/libavcodec.a __TEXT,__text reloc 12: R_ABS reloc but no absolute symbol at target address for architecture armv7

According to this link, I should download the newer gas-preprocessor
http://stackoverflow.com/questions/13944482/compiling-ffmpeg-for-ios-r-abs-reloc-error

I check my pas-preprocessor version. It's latest version which i clone from there:
https://github.com/yuvi/gas-preprocessor

Do you know how to fix it.

**Comment by Ronan0912** [comment]
Thank you for the modifications that you made on your script. With the 1.2.1 version of ffmpeg, it compiles for the armv7 without any problem on my mac. I don't know how to fix your error but it must come from your configuration (maybe like you said a bad version of the gas-preprocessor...).
I am using the ffmpeg library to encode and decode a video feed with the h264 codec on an iPhone 5. Currently, there are several linking errors that I am trying to resolve ... 

Ronan
