### ISSUE TITLE
Compilation fails with iOS 7.0

### ISSUE THREAD

**Issue by Ronan0912** [lvjian700/ffmpegc#3]
It looks like that the script doesn't work with the new release of iOS and Xcode tools :

"compile armv7 ...
Makefile:3: config.mak: No such file or directory
cat: config.h: No such file or directory
./configure
Found no assembler
Minimum version is yasm-1.2.0
If you really want to compile without asm, configure with --disable-asm.
make: **\* [config.mak] Error 1
Unknown option --disable-shared, ignored
No working C compiler found.
Makefile:3: config.mak: No such file or directory
cat: config.h: No such file or directory
./configure
Found no assembler
Minimum version is yasm-1.2.0
If you really want to compile without asm, configure with --disable-asm.
make: **\* [config.mak] Error 1
Makefile:2: config.mak: No such file or directory
Makefile:49: /common.mak: No such file or directory
Makefile:92: /libavutil/Makefile: No such file or directory
Makefile:92: /library.mak: No such file or directory
Makefile:178: /doc/Makefile: No such file or directory
Makefile:179: /tests/Makefile: No such file or directory
make: **\* No rule to make target `/tests/Makefile'.  Stop.
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/gcc is unable to create an executable file.
C compiler test failed."

**Comment by lvjian700** [comment]
Minimum version is yasm-1.2.0。
brew update 
brew info yasm
brew install yasm

After that, I find more error. I'm trying to fix it.

**Comment by Ronan0912** [comment]
"LLVM-GCC is not included in Xcode 5" (https://developer.apple.com/library/ios/documentation/DeveloperTools/Conceptual/WhatsNewXcode/Articles/xcode_5_0.html)
Clang++ has to be used : "xcrun -find -sdk iphoneos clang++" from the default toolchain.
