### ISSUE TITLE
Compiling for SDK 7.1

### ISSUE THREAD

**Issue by davealma** [lvjian700/ffmpegc#4]
There is a problem when I try to compile for the SDK 7.1!! What should be done to fix this issue??

**Comment by lvjian700** [comment]
I'm not test it on iOS 7.1.
plz, commit your error logs.

@davealma

**Comment by davealma** [comment]
When I want to compile it throws this error:
Unable to identify target architecture at /usr/bin/gas-preprocessor.pl line 82.
AS  libavcodec/arm/vp8dsp_armv6.o
libavcodec/arm/vp8dsp_armv6.S:2228:11: error: branch target out of range
        b vp8_put_epel_h6_armv6 + 4
          ^
libavcodec/arm/vp8dsp_armv6.S:2247:11: error: branch target out of range
        b vp8_put_epel_v6_armv6 + 4
          ^
libavcodec/arm/vp8dsp_armv6.S:2266:11: error: branch target out of range
        b vp8_put_epel_h6_armv6 + 4
          ^
libavcodec/arm/vp8dsp_armv6.S:2285:11: error: branch target out of range
        b vp8_put_epel_v6_armv6 + 4
          ^
libavcodec/arm/vp8dsp_armv6.S:2304:11: error: branch target out of range
        b vp8_put_epel_h4_armv6 + 4
          ^
libavcodec/arm/vp8dsp_armv6.S:2323:11: error: branch target out of range
        b vp8_put_epel_v4_armv6 + 4
          ^
libavcodec/arm/vp8dsp_armv6.S:2342:11: error: branch target out of range
        b vp8_put_epel_h6_armv6 + 4
          ^
libavcodec/arm/vp8dsp_armv6.S:2361:11: error: branch target out of range
        b vp8_put_epel_v6_armv6 + 4
          ^
libavcodec/arm/vp8dsp_armv6.S:2380:11: error: branch target out of range
        b vp8_put_epel_h4_armv6 + 4
          ^
libavcodec/arm/vp8dsp_armv6.S:2399:11: error: branch target out of range
        b vp8_put_epel_v4_armv6 + 4
          ^
libavcodec/arm/vp8dsp_armv6.S:2419:11: error: branch target out of range
        b vp8_put_bilin_h_armv6 + 4
          ^
libavcodec/arm/vp8dsp_armv6.S:2438:11: error: branch target out of range
        b vp8_put_bilin_v_armv6 + 4
          ^
libavcodec/arm/vp8dsp_armv6.S:2457:11: error: branch target out of range
        b vp8_put_bilin_h_armv6 + 4
          ^
libavcodec/arm/vp8dsp_armv6.S:2476:11: error: branch target out of range
        b vp8_put_bilin_v_armv6 + 4
          ^
libavcodec/arm/vp8dsp_armv6.S:2495:11: error: branch target out of range
        b vp8_put_bilin_h_armv6 + 4
          ^
libavcodec/arm/vp8dsp_armv6.S:2514:11: error: branch target out of range
        b vp8_put_bilin_v_armv6 + 4
make: **\* [libavcodec/arm/vp8dsp_armv6.o] Error 1

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: archive member: libavfilter/libavfilter.a(bbox.o) cputype (12) does not match previous archive members cputype (7) (all members must match)
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: archive member: libavfilter/libavfilter.a(bbox.o) cputype (12) does not match previous archive members cputype (7) (all members must match)
make: **\* [libavfilter/libavfilter.a] Error 1
./install-ffmpeg.sh: line 100: cd: /Users/david/Documents/FFmpeg-iOSProject/ffmpegc-master/build/built/armv7/lib: No such file or directory

**Comment by lvjian700** [comment]
@davealma 
 "/usr/bin/gas-preprocessor.pl"  is a old version. You should remove it.
After that, run ./install-gas.sh 
The gas-preprocessor.pl file will install to the path: "/usr/sbin/gas-preprocessor.pl"

**Comment by lvjian700** [comment]
@davealma 
BTW. I'm not sure, this script can compile ffmpeg for armv6.  
If you want work with armv6, you can fork the repository and DIY.

**Comment by davealma** [comment]
I don't want to compile armv6! I want to compile to armv7 but with SDK 7.1, as you suggest I use the gas-preprocessor.pl download by runing the script install-gas.sh I check and the pl file is in /usr/sbin/gas-preprocessor.pl!
Really is rare that it tries to compile for armv6 since I don't input that parameter in the pl file! I check in the install-ffmpeg.sh and only declares the following architectures ARCHS="armv7 armv7s i386"

**Comment by tuchangwei** [comment]
Hi, I have the same issue:
Unable to identify target architecture at /usr/sbin/gas-preprocessor.pl line 82.

## Under Mac OX 10.9, Xcode 5.1.

OK, I add "--disable-armv6 \
    --disable-armv6t2 \" behind of "./configure ", everything works well.

**Comment by LionelWang** [comment]
There is a problem when I try to compile for the SDK 7.1!! What should be done to fix this issue??
When I want to compile it throws this error:
/Users/LionelWang/Documents/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: archive member: libavfilter/libavfilter.a(bbox.o) cputype (12) does not match previous archive members cputype (7) (all members must match)
/Users/LionelWang/Documents/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: archive member: libavfilter/libavfilter.a(bbox.o) cputype (12) does not match previous archive members cputype (7) (all members must match)
make: **\* [libavfilter/libavfilter.a] Error 1
./install-ffmpeg.sh: line 100: cd: /Users/LionelWang/Documents/ffmpegc/build/built/armv7/lib: No such file or directory

PS：./install-ffmpeg.sh: line 100  is  “ cd "${INTERDIR}/armv7/lib"  ”。

**Comment by lvjian700** [comment]
thanks for @tuchangwei  .
gas-preprocessor error has been fixed.

**Comment by lvjian700** [comment]
@LionelWang 
plz check this link turn off asm
http://stackoverflow.com/questions/8694676/compiling-64-bit-flac-libflac-in-os-x-lion

**Comment by LionelWang** [comment]
@lvjian700 
OK,  I add "--disable-asm" behind of "./configure ", everything works well.

**Comment by zhangcan850718** [comment]
Hi,lvjian700,There are two problems when I try to compile for the SDK 7.0! What should be done to fix this issue?
first--------------------------------------------------------------------------------------------------------------------------
Unable to identify target architecture at /usr/sbin/gas-preprocessor.pl line 82.
AS  libavcodec/arm/aacpsdsp_neon.o
Unable to identify target architecture at /usr/sbin/gas-preprocessor.pl line 82.
AS  libavcodec/arm/ac3dsp_arm.o
CC  libavcodec/arm/ac3dsp_init_arm.o
Unable to identify target architecture at /usr/sbin/gas-preprocessor.pl line 82.
AS  libavcodec/arm/ac3dsp_neon.o
CC  libavcodec/arm/dcadsp_init_arm.o
Unable to identify target architecture at /usr/sbin/gas-preprocessor.pl line 82.
AS  libavcodec/arm/dcadsp_neon.o
Unable to identify target architecture at /usr/sbin/gas-preprocessor.pl line 82.
AS  libavcodec/arm/dcadsp_vfp.o
Unable to identify target architecture at /usr/sbin/gas-preprocessor.pl line 82.
AS  libavcodec/arm/dsputil_arm.o
CC  libavcodec/arm/dsputil_init_arm.o
CC  libavcodec/arm/dsputil_init_neon.o
Unable to identify target architecture at /usr/sbin/gas-preprocessor.pl line 82.
AS  libavcodec/arm/dsputil_neon.o
CC  libavcodec/arm/fft_fixed_init_arm.o
Unable to identify target architecture at /usr/sbin/gas-preprocessor.pl line 82.
AS  libavcodec/arm/fft_fixed_neon.o
CC  libavcodec/arm/fft_init_arm.o
Unable to identify target architecture at /usr/sbin/gas-preprocessor.pl line 82.
AS  libavcodec/arm/fft_neon.o
Unable to identify target architecture at /usr/sbin/gas-preprocessor.pl line 82.
AS  libavcodec/arm/fft_vfp.o
Unable to identify target architecture at /usr/sbin/gas-preprocessor.pl line 82.
AS  libavcodec/arm/flacdsp_arm.o
CC  libavcodec/arm/flacdsp_init_arm.o
CC  libavcodec/arm/fmtconvert_init_arm.o
Unable to identify target architecture at /usr/sbin/gas-preprocessor.pl line 82.
AS  libavcodec/arm/fmtconvert_neon.o
Unable to identify target architecture at /usr/sbin/gas-preprocessor.pl line 82.
AS  libavcodec/arm/fmtconvert_vfp.o
CC  libavcodec/arm/h264chroma_init_arm.o
Unable to identify target architecture at /usr/sbin/gas-preprocessor.pl line 82.
AS  libavcodec/arm/h264cmc_neon.o
CC  libavcodec/arm/h264dsp_init_arm.o
Unable to identify target architecture at /usr/sbin/gas-preprocessor.pl line 82.
AS  libavcodec/arm/h264dsp_neon.o
Unable to identify target architecture at /usr/sbin/gas-preprocessor.pl line 82.
AS  libavcodec/arm/h264idct_neon.o
CC  libavcodec/arm/h264pred_init_arm.o
Unable to identify target architecture at /usr/sbin/gas-preprocessor.pl line 82.
AS  libavcodec/arm/h264pred_neon.o
CC  libavcodec/arm/h264qpel_init_arm.o
Unable to identify target architecture at /usr/sbin/gas-preprocessor.pl line 82.
AS  libavcodec/arm/h264qpel_neon.o
Unable to identify target architecture at /usr/sbin/gas-preprocessor.pl line 82.
AS  libavcodec/arm/hpeldsp_arm.o
CC  libavcodec/arm/hpeldsp_init_arm.o
CC  libavcodec/arm/hpeldsp_init_neon.o
Unable to identify target architecture at /usr/sbin/gas-preprocessor.pl line 82.
AS  libavcodec/arm/hpeldsp_neon.o
Unable to identify target architecture at /usr/sbin/gas-preprocessor.pl line 82.
AS  libavcodec/arm/int_neon.o
Unable to identify target architecture at /usr/sbin/gas-preprocessor.pl line 82.
AS  libavcodec/arm/jrevdct_arm.o
Unable to identify target architecture at /usr/sbin/gas-preprocessor.pl line 82.
AS  libavcodec/arm/mdct_fixed_neon.o
Unable to identify target architecture at /usr/sbin/gas-preprocessor.pl line 82.
AS  libavcodec/arm/mdct_neon.o
Unable to identify target architecture at /usr/sbin/gas-preprocessor.pl line 82.
AS  libavcodec/arm/mdct_vfp.o
CC  libavcodec/arm/mpegaudiodsp_init_arm.o
CC  libavcodec/arm/mpegvideo_arm.o
Unable to identify target architecture at /usr/sbin/gas-preprocessor.pl line 82.
AS  libavcodec/arm/mpegvideo_neon.o
Unable to identify target architecture at /usr/sbin/gas-preprocessor.pl line 82.
AS  libavcodec/arm/rdft_neon.o
CC  libavcodec/arm/rv34dsp_init_arm.o
Unable to identify target architecture at /usr/sbin/gas-preprocessor.pl line 82.
AS  libavcodec/arm/rv34dsp_neon.o
CC  libavcodec/arm/rv40dsp_init_arm.o
Unable to identify target architecture at /usr/sbin/gas-preprocessor.pl line 82.
AS  libavcodec/arm/rv40dsp_neon.o
CC  libavcodec/arm/sbrdsp_init_arm.o
Unable to identify target architecture at /usr/sbin/gas-preprocessor.pl line 82.
AS  libavcodec/arm/sbrdsp_neon.o
Unable to identify target architecture at /usr/sbin/gas-preprocessor.pl line 82.
AS  libavcodec/arm/simple_idct_arm.o
Unable to identify target architecture at /usr/sbin/gas-preprocessor.pl line 82.
AS  libavcodec/arm/simple_idct_neon.o
Unable to identify target architecture at /usr/sbin/gas-preprocessor.pl line 82.
AS  libavcodec/arm/synth_filter_neon.o
Unable to identify target architecture at /usr/sbin/gas-preprocessor.pl line 82.
AS  libavcodec/arm/synth_filter_vfp.o
CC  libavcodec/arm/vc1dsp_init_arm.o
CC  libavcodec/arm/vc1dsp_init_neon.o
Unable to identify target architecture at /usr/sbin/gas-preprocessor.pl line 82.
AS  libavcodec/arm/vc1dsp_neon.o
libavcodec/arm/vc1dsp_neon.S:751:10: error: unexpected token in argument list
  ra .dn d28.i8
         ^
libavcodec/arm/vc1dsp_neon.S:752:10: error: unexpected token in argument list
  rb .dn d29.i8
         ^
libavcodec/arm/vc1dsp_neon.S:753:10: error: unexpected token in argument list
  rc .dn d30.i8
         ^
libavcodec/arm/vc1dsp_neon.S:754:10: error: unexpected token in argument list
  rd .dn d31.i8
         ^
libavcodec/arm/vc1dsp_neon.S:757:14: error: invalid operand for instruction
        vmov ra, #4 
             ^
libavcodec/arm/vc1dsp_neon.S:758:14: error: invalid operand for instruction
        vmov rb, #53 
             ^
libavcodec/arm/vc1dsp_neon.S:759:14: error: invalid operand for instruction
        vmov rc, #18 
             ^
libavcodec/arm/vc1dsp_neon.S:760:14: error: invalid operand for instruction
        vmov rd, #3 
             ^
libavcodec/arm/vc1dsp_neon.S:864:10: error: unexpected token in argument list
  ra .dn d28.i16
         ^
libavcodec/arm/vc1dsp_neon.S:865:10: error: unexpected token in argument list
  rb .dn d29.i16
         ^
libavcodec/arm/vc1dsp_neon.S:866:10: error: unexpected token in argument list
  rc .dn d30.i16
         ^
libavcodec/arm/vc1dsp_neon.S:867:10: error: unexpected token in argument list
  rd .dn d31.i16
         ^
libavcodec/arm/vc1dsp_neon.S:870:14: error: invalid operand for instruction
        vmov ra, #4 
             ^
libavcodec/arm/vc1dsp_neon.S:871:14: error: invalid operand for instruction
        vmov rb, #53 
             ^
libavcodec/arm/vc1dsp_neon.S:872:14: error: invalid operand for instruction
        vmov rc, #18 
             ^
libavcodec/arm/vc1dsp_neon.S:873:14: error: invalid operand for instruction
        vmov rd, #3 
             ^
libavcodec/arm/vc1dsp_neon.S:940:10: error: unexpected token in argument list
  ra .dn d28.i8
         ^
libavcodec/arm/vc1dsp_neon.S:941:10: error: unexpected token in argument list
  rb .dn d29.i8
         ^
libavcodec/arm/vc1dsp_neon.S:942:10: error: unexpected token in argument list
  rc .dn d30.i8
         ^
libavcodec/arm/vc1dsp_neon.S:943:10: error: unexpected token in argument list
  rd .dn d31.i8
         ^
libavcodec/arm/vc1dsp_neon.S:946:14: error: invalid operand for instruction
        vmov rb, #9 
             ^
libavcodec/arm/vc1dsp_neon.S:1050:10: error: unexpected token in argument list
  ra .dn d28.i16
         ^
libavcodec/arm/vc1dsp_neon.S:1051:10: error: unexpected token in argument list
  rb .dn d29.i16
         ^
libavcodec/arm/vc1dsp_neon.S:1052:10: error: unexpected token in argument list
  rc .dn d30.i16
         ^
libavcodec/arm/vc1dsp_neon.S:1053:10: error: unexpected token in argument list
  rd .dn d31.i16
         ^
libavcodec/arm/vc1dsp_neon.S:1056:14: error: invalid operand for instruction
        vmov ra, #4 
             ^
libavcodec/arm/vc1dsp_neon.S:1057:14: error: invalid operand for instruction
        vmov rb, #53 
             ^
libavcodec/arm/vc1dsp_neon.S:1058:14: error: invalid operand for instruction
        vmov rc, #18 
             ^
libavcodec/arm/vc1dsp_neon.S:1059:14: error: invalid operand for instruction
        vmov rd, #3 
             ^
libavcodec/arm/vc1dsp_neon.S:1126:10: error: unexpected token in argument list
  ra .dn d28.i8
         ^
libavcodec/arm/vc1dsp_neon.S:1127:10: error: unexpected token in argument list
  rb .dn d29.i8
         ^
libavcodec/arm/vc1dsp_neon.S:1128:10: error: unexpected token in argument list
  rc .dn d30.i8
         ^
libavcodec/arm/vc1dsp_neon.S:1129:10: error: unexpected token in argument list
  rd .dn d31.i8
         ^
libavcodec/arm/vc1dsp_neon.S:1132:14: error: invalid operand for instruction
        vmov ra, #3 
             ^
libavcodec/arm/vc1dsp_neon.S:1133:14: error: invalid operand for instruction
        vmov rb, #18 
             ^
libavcodec/arm/vc1dsp_neon.S:1134:14: error: invalid operand for instruction
        vmov rc, #53 
             ^
libavcodec/arm/vc1dsp_neon.S:1135:14: error: invalid operand for instruction
        vmov rd, #4 
             ^
libavcodec/arm/vc1dsp_neon.S:1239:10: error: unexpected token in argument list
  ra .dn d28.i16
         ^
libavcodec/arm/vc1dsp_neon.S:1240:10: error: unexpected token in argument list
  rb .dn d29.i16
         ^
libavcodec/arm/vc1dsp_neon.S:1241:10: error: unexpected token in argument list
  rc .dn d30.i16
         ^
libavcodec/arm/vc1dsp_neon.S:1242:10: error: unexpected token in argument list
  rd .dn d31.i16
         ^
libavcodec/arm/vc1dsp_neon.S:1245:14: error: invalid operand for instruction
        vmov ra, #4 
             ^
libavcodec/arm/vc1dsp_neon.S:1246:14: error: invalid operand for instruction
        vmov rb, #53 
             ^
libavcodec/arm/vc1dsp_neon.S:1247:14: error: invalid operand for instruction
        vmov rc, #18 
             ^
libavcodec/arm/vc1dsp_neon.S:1248:14: error: invalid operand for instruction
        vmov rd, #3 
             ^
libavcodec/arm/vc1dsp_neon.S:1315:10: error: unexpected token in argument list
  ra .dn d28.i8
         ^
libavcodec/arm/vc1dsp_neon.S:1316:10: error: unexpected token in argument list
  rb .dn d29.i8
         ^
libavcodec/arm/vc1dsp_neon.S:1317:10: error: unexpected token in argument list
  rc .dn d30.i8
         ^
libavcodec/arm/vc1dsp_neon.S:1318:10: error: unexpected token in argument list
  rd .dn d31.i8
         ^
libavcodec/arm/vc1dsp_neon.S:1321:14: error: invalid operand for instruction
        vmov ra, #4 
             ^
libavcodec/arm/vc1dsp_neon.S:1322:14: error: invalid operand for instruction
        vmov rb, #53 
             ^
libavcodec/arm/vc1dsp_neon.S:1323:14: error: invalid operand for instruction
        vmov rc, #18 
             ^
libavcodec/arm/vc1dsp_neon.S:1324:14: error: invalid operand for instruction
        vmov rd, #3 
             ^
libavcodec/arm/vc1dsp_neon.S:1428:10: error: unexpected token in argument list
  ra .dn d28.i16
         ^
libavcodec/arm/vc1dsp_neon.S:1429:10: error: unexpected token in argument list
  rb .dn d29.i16
         ^
libavcodec/arm/vc1dsp_neon.S:1430:10: error: unexpected token in argument list
  rc .dn d30.i16
         ^
libavcodec/arm/vc1dsp_neon.S:1431:10: error: unexpected token in argument list
  rd .dn d31.i16
         ^
libavcodec/arm/vc1dsp_neon.S:1434:14: error: invalid operand for instruction
        vmov rb, #9 
             ^
libavcodec/arm/vc1dsp_neon.S:1498:10: error: unexpected token in argument list
  ra .dn d28.i8
         ^
libavcodec/arm/vc1dsp_neon.S:1499:10: error: unexpected token in argument list
  rb .dn d29.i8
         ^
libavcodec/arm/vc1dsp_neon.S:1500:10: error: unexpected token in argument list
  rc .dn d30.i8
         ^
libavcodec/arm/vc1dsp_neon.S:1501:10: error: unexpected token in argument list
  rd .dn d31.i8
         ^
libavcodec/arm/vc1dsp_neon.S:1504:14: error: invalid operand for instruction
        vmov rb, #9 
             ^
libavcodec/arm/vc1dsp_neon.S:1608:10: error: unexpected token in argument list
  ra .dn d28.i16
         ^
libavcodec/arm/vc1dsp_neon.S:1609:10: error: unexpected token in argument list
  rb .dn d29.i16
         ^
libavcodec/arm/vc1dsp_neon.S:1610:10: error: unexpected token in argument list
  rc .dn d30.i16
         ^
libavcodec/arm/vc1dsp_neon.S:1611:10: error: unexpected token in argument list
  rd .dn d31.i16
         ^
libavcodec/arm/vc1dsp_neon.S:1614:14: error: invalid operand for instruction
        vmov rb, #9 
             ^
libavcodec/arm/vc1dsp_neon.S:1679:10: error: unexpected token in argument list
  ra .dn d28.i8
         ^
libavcodec/arm/vc1dsp_neon.S:1680:10: error: unexpected token in argument list
  rb .dn d29.i8
         ^
libavcodec/arm/vc1dsp_neon.S:1681:10: error: unexpected token in argument list
  rc .dn d30.i8
         ^
libavcodec/arm/vc1dsp_neon.S:1682:10: error: unexpected token in argument list
  rd .dn d31.i8
         ^
libavcodec/arm/vc1dsp_neon.S:1685:14: error: invalid operand for instruction
        vmov ra, #3 
             ^
libavcodec/arm/vc1dsp_neon.S:1686:14: error: invalid operand for instruction
        vmov rb, #18 
             ^
libavcodec/arm/vc1dsp_neon.S:1687:14: error: invalid operand for instruction
        vmov rc, #53 
             ^
libavcodec/arm/vc1dsp_neon.S:1688:14: error: invalid operand for instruction
        vmov rd, #4 
             ^
libavcodec/arm/vc1dsp_neon.S:1792:10: error: unexpected token in argument list
  ra .dn d28.i16
         ^
libavcodec/arm/vc1dsp_neon.S:1793:10: error: unexpected token in argument list
  rb .dn d29.i16
         ^
libavcodec/arm/vc1dsp_neon.S:1794:10: error: unexpected token in argument list
  rc .dn d30.i16
         ^
libavcodec/arm/vc1dsp_neon.S:1795:10: error: unexpected token in argument list
  rd .dn d31.i16
         ^
libavcodec/arm/vc1dsp_neon.S:1798:14: error: invalid operand for instruction
        vmov rb, #9 
             ^
libavcodec/arm/vc1dsp_neon.S:1863:10: error: unexpected token in argument list
  ra .dn d28.i8
         ^
libavcodec/arm/vc1dsp_neon.S:1864:10: error: unexpected token in argument list
  rb .dn d29.i8
         ^
libavcodec/arm/vc1dsp_neon.S:1865:10: error: unexpected token in argument list
  rc .dn d30.i8
         ^
libavcodec/arm/vc1dsp_neon.S:1866:10: error: unexpected token in argument list
  rd .dn d31.i8
         ^
libavcodec/arm/vc1dsp_neon.S:1869:14: error: invalid operand for instruction
        vmov ra, #4 
             ^
libavcodec/arm/vc1dsp_neon.S:1870:14: error: invalid operand for instruction
        vmov rb, #53 
             ^
libavcodec/arm/vc1dsp_neon.S:1871:14: error: invalid operand for instruction
        vmov rc, #18 
             ^
libavcodec/arm/vc1dsp_neon.S:1872:14: error: invalid operand for instruction
        vmov rd, #3 
             ^
libavcodec/arm/vc1dsp_neon.S:1976:10: error: unexpected token in argument list
  ra .dn d28.i16
         ^
libavcodec/arm/vc1dsp_neon.S:1977:10: error: unexpected token in argument list
  rb .dn d29.i16
         ^
libavcodec/arm/vc1dsp_neon.S:1978:10: error: unexpected token in argument list
  rc .dn d30.i16
         ^
libavcodec/arm/vc1dsp_neon.S:1979:10: error: unexpected token in argument list
  rd .dn d31.i16
         ^
libavcodec/arm/vc1dsp_neon.S:1982:14: error: invalid operand for instruction
        vmov ra, #3 
             ^
libavcodec/arm/vc1dsp_neon.S:1983:14: error: invalid operand for instruction
        vmov rb, #18 
             ^
libavcodec/arm/vc1dsp_neon.S:1984:14: error: invalid operand for instruction
        vmov rc, #53 
             ^
libavcodec/arm/vc1dsp_neon.S:1985:14: error: invalid operand for instruction
        vmov rd, #4 
             ^
libavcodec/arm/vc1dsp_neon.S:2052:10: error: unexpected token in argument list
  ra .dn d28.i8
         ^
libavcodec/arm/vc1dsp_neon.S:2053:10: error: unexpected token in argument list
  rb .dn d29.i8
         ^
libavcodec/arm/vc1dsp_neon.S:2054:10: error: unexpected token in argument list
  rc .dn d30.i8
         ^
libavcodec/arm/vc1dsp_neon.S:2055:10: error: unexpected token in argument list
  rd .dn d31.i8
         ^
libavcodec/arm/vc1dsp_neon.S:2058:14: error: invalid operand for instruction
        vmov rb, #9 
             ^
libavcodec/arm/vc1dsp_neon.S:2162:10: error: unexpected token in argument list
  ra .dn d28.i16
         ^
libavcodec/arm/vc1dsp_neon.S:2163:10: error: unexpected token in argument list
  rb .dn d29.i16
         ^
libavcodec/arm/vc1dsp_neon.S:2164:10: error: unexpected token in argument list
  rc .dn d30.i16
         ^
libavcodec/arm/vc1dsp_neon.S:2165:10: error: unexpected token in argument list
  rd .dn d31.i16
         ^
libavcodec/arm/vc1dsp_neon.S:2168:14: error: invalid operand for instruction
        vmov ra, #3 
             ^
libavcodec/arm/vc1dsp_neon.S:2169:14: error: invalid operand for instruction
        vmov rb, #18 
             ^
libavcodec/arm/vc1dsp_neon.S:2170:14: error: invalid operand for instruction
        vmov rc, #53 
             ^
libavcodec/arm/vc1dsp_neon.S:2171:14: error: invalid operand for instruction
        vmov rd, #4 
             ^
libavcodec/arm/vc1dsp_neon.S:2238:10: error: unexpected token in argument list
  ra .dn d28.i8
         ^
libavcodec/arm/vc1dsp_neon.S:2239:10: error: unexpected token in argument list
  rb .dn d29.i8
         ^
libavcodec/arm/vc1dsp_neon.S:2240:10: error: unexpected token in argument list
  rc .dn d30.i8
         ^
libavcodec/arm/vc1dsp_neon.S:2241:10: error: unexpected token in argument list
  rd .dn d31.i8
         ^
libavcodec/arm/vc1dsp_neon.S:2244:14: error: invalid operand for instruction
        vmov ra, #3 
             ^
libavcodec/arm/vc1dsp_neon.S:2245:14: error: invalid operand for instruction
        vmov rb, #18 
             ^
libavcodec/arm/vc1dsp_neon.S:2246:14: error: invalid operand for instruction
        vmov rc, #53 
             ^
libavcodec/arm/vc1dsp_neon.S:2247:14: error: invalid operand for instruction
        vmov rd, #4 
             ^
libavcodec/arm/vc1dsp_neon.S:2351:10: error: unexpected token in argument list
  ra .dn d28.i16
         ^
libavcodec/arm/vc1dsp_neon.S:2352:10: error: unexpected token in argument list
  rb .dn d29.i16
         ^
libavcodec/arm/vc1dsp_neon.S:2353:10: error: unexpected token in argument list
  rc .dn d30.i16
         ^
libavcodec/arm/vc1dsp_neon.S:2354:10: error: unexpected token in argument list
  rd .dn d31.i16
         ^
libavcodec/arm/vc1dsp_neon.S:2357:14: error: invalid operand for instruction
        vmov ra, #3 
             ^
libavcodec/arm/vc1dsp_neon.S:2358:14: error: invalid operand for instruction
        vmov rb, #18 
             ^
libavcodec/arm/vc1dsp_neon.S:2359:14: error: invalid operand for instruction
        vmov rc, #53 
             ^
libavcodec/arm/vc1dsp_neon.S:2360:14: error: invalid operand for instruction
        vmov rd, #4 
             ^
libavcodec/arm/vc1dsp_neon.S:2425:10: error: unexpected token in argument list
  ra .dn d28.i8
         ^
libavcodec/arm/vc1dsp_neon.S:2426:10: error: unexpected token in argument list
  rb .dn d29.i8
         ^
libavcodec/arm/vc1dsp_neon.S:2427:10: error: unexpected token in argument list
  rc .dn d30.i8
         ^
libavcodec/arm/vc1dsp_neon.S:2428:10: error: unexpected token in argument list
  rd .dn d31.i8
         ^
libavcodec/arm/vc1dsp_neon.S:2431:14: error: invalid operand for instruction
        vmov ra, #4 
             ^
libavcodec/arm/vc1dsp_neon.S:2432:14: error: invalid operand for instruction
        vmov rb, #53 
             ^
libavcodec/arm/vc1dsp_neon.S:2433:14: error: invalid operand for instruction
        vmov rc, #18 
             ^
libavcodec/arm/vc1dsp_neon.S:2434:14: error: invalid operand for instruction
        vmov rd, #3 
             ^
libavcodec/arm/vc1dsp_neon.S:2484:10: error: unexpected token in argument list
  ra .dn d28.i8
         ^
libavcodec/arm/vc1dsp_neon.S:2485:10: error: unexpected token in argument list
  rb .dn d29.i8
         ^
libavcodec/arm/vc1dsp_neon.S:2486:10: error: unexpected token in argument list
  rc .dn d30.i8
         ^
libavcodec/arm/vc1dsp_neon.S:2487:10: error: unexpected token in argument list
  rd .dn d31.i8
         ^
libavcodec/arm/vc1dsp_neon.S:2490:14: error: invalid operand for instruction
        vmov rb, #9 
             ^
libavcodec/arm/vc1dsp_neon.S:2540:10: error: unexpected token in argument list
  ra .dn d28.i8
         ^
libavcodec/arm/vc1dsp_neon.S:2541:10: error: unexpected token in argument list
  rb .dn d29.i8
         ^
libavcodec/arm/vc1dsp_neon.S:2542:10: error: unexpected token in argument list
  rc .dn d30.i8
         ^
libavcodec/arm/vc1dsp_neon.S:2543:10: error: unexpected token in argument list
  rd .dn d31.i8
         ^
libavcodec/arm/vc1dsp_neon.S:2546:14: error: invalid operand for instruction
        vmov ra, #3 
             ^
libavcodec/arm/vc1dsp_neon.S:2547:14: error: invalid operand for instruction
        vmov rb, #18 
             ^
libavcodec/arm/vc1dsp_neon.S:2548:14: error: invalid operand for instruction
        vmov rc, #53 
             ^
libavcodec/arm/vc1dsp_neon.S:2549:14: error: invalid operand for instruction
        vmov rd, #4 
             ^
libavcodec/arm/vc1dsp_neon.S:2608:10: error: unexpected token in argument list
  ra .dn d28.i8
         ^
libavcodec/arm/vc1dsp_neon.S:2609:10: error: unexpected token in argument list
  rb .dn d29.i8
         ^
libavcodec/arm/vc1dsp_neon.S:2610:10: error: unexpected token in argument list
  rc .dn d30.i8
         ^
libavcodec/arm/vc1dsp_neon.S:2611:10: error: unexpected token in argument list
  rd .dn d31.i8
         ^
libavcodec/arm/vc1dsp_neon.S:2614:14: error: invalid operand for instruction
        vmov ra, #4 
             ^
libavcodec/arm/vc1dsp_neon.S:2615:14: error: invalid operand for instruction
        vmov rb, #53 
             ^
libavcodec/arm/vc1dsp_neon.S:2616:14: error: invalid operand for instruction
        vmov rc, #18 
             ^
libavcodec/arm/vc1dsp_neon.S:2617:14: error: invalid operand for instruction
        vmov rd, #3 
             ^
libavcodec/arm/vc1dsp_neon.S:2699:10: error: unexpected token in argument list
  ra .dn d28.i8
         ^
libavcodec/arm/vc1dsp_neon.S:2700:10: error: unexpected token in argument list
  rb .dn d29.i8
         ^
libavcodec/arm/vc1dsp_neon.S:2701:10: error: unexpected token in argument list
  rc .dn d30.i8
         ^
libavcodec/arm/vc1dsp_neon.S:2702:10: error: unexpected token in argument list
  rd .dn d31.i8
         ^
libavcodec/arm/vc1dsp_neon.S:2705:14: error: invalid operand for instruction
        vmov rb, #9 
             ^
libavcodec/arm/vc1dsp_neon.S:2787:10: error: unexpected token in argument list
  ra .dn d28.i8
         ^
libavcodec/arm/vc1dsp_neon.S:2788:10: error: unexpected token in argument list
  rb .dn d29.i8
         ^
libavcodec/arm/vc1dsp_neon.S:2789:10: error: unexpected token in argument list
  rc .dn d30.i8
         ^
libavcodec/arm/vc1dsp_neon.S:2790:10: error: unexpected token in argument list
  rd .dn d31.i8
         ^
libavcodec/arm/vc1dsp_neon.S:2793:14: error: invalid operand for instruction
        vmov ra, #3 
             ^
libavcodec/arm/vc1dsp_neon.S:2794:14: error: invalid operand for instruction
        vmov rb, #18 
             ^
libavcodec/arm/vc1dsp_neon.S:2795:14: error: invalid operand for instruction
        vmov rc, #53 
             ^
libavcodec/arm/vc1dsp_neon.S:2796:14: error: invalid operand for instruction
        vmov rd, #4 
             ^
make: **\* [libavcodec/arm/vc1dsp_neon.o] Error 1
second---------------------------------------------------------------------------------------------------------------------
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: archive member: libavfilter/libavfilter.a(bbox.o) cputype (12) does not match previous archive members cputype (7) (all members must match)
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: archive member: libavfilter/libavfilter.a(bbox.o) cputype (12) does not match previous archive members cputype (7) (all members must match)
make: **\* [libavfilter/libavfilter.a] Error 1
./install-ffmpeg.sh: line 100: cd: /Volumes/partion2/ffmpegc/build/built/armv7/lib: No such file or directory
